
export const FETCH_COUNTRY_REQUEST = 'FETCH_COUNTRY_REQUEST';
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS';

export const FETCH_CONTINENT_REQUEST = 'FETCH_CONTINENT_REQUEST';
export const FETCH_CONTINENT_SUCCESS = 'FETCH_CONTINENT_SUCCESS';